version: "3.0"

services:
    db:
        container_name: "db"
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
        networks:
            - custom
    app:
        container_name: app
        image: project1_app
        environment:
            REAL_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/postgres"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:8000"
        networks:
            - custom

networks:
    custom:
        driver: bridge
