"""add column password

Revision ID: fccdea596e3a
Revises: 132410b5beab
Create Date: 2024-01-26 15:04:07.618930

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "fccdea596e3a"
down_revision = "132410b5beab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
